apiVersion: v1
kind: ConfigMap
metadata:
  name: aris-proxy-api-config
  namespace: aris-proxy-api
data:
  PORT: "8080"
  READ_TIMEOUT: "10s"
  WRITE_TIMEOUT: "5m"
  MAX_HEADER_BYTES: "1048576"
  LOG_LEVLE: "INFO"
  LOG_DIR: "./logs"
  OAUTH2_STATE_STRING: "REPLACE_ME"
  OAUTH2_GITHUB_CLIENT_ID: "REPLACE_ME"
  OAUTH2_GITHUB_REDIRECT_URL: "http://0.0.0.0:8080/web/login"
  OAUTH2_GOOGLE_CLIENT_ID: "REPLACE_ME"
  OAUTH2_GOOGLE_CLIENT_SECRET: "REPLACE_ME"
  OAUTH2_GOOGLE_REDIRECT_URL: "http://0.0.0.0:8080/web/login"
  POSTGRES_USER: "hcd233"
  POSTGRES_DATABASE: "tmpl-db"
  POSTGRES_HOST: "REPLACE_ME"
  POSTGRES_PORT: "5432"
  POSTGRES_SSLMODE: "disable"
  REDIS_HOST: "REPLACE_ME"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "REPLACE_ME"
  MINIO_TLS: "false"
  POOL_WORKERS: "8"
  POOL_QUEUE_SIZE: "100"
  SQL_BATCH_SIZE: "500"
  TRUSTED_PROXIES: "REPLACE_ME"
  CLS_ENDPOINT: "ap-guangzhou.cls.tencentcs.com"
  CLS_LEVEL: "INFO"
  CLS_TOPIC_ID: "REPLACE_ME"
  JWT_ACCESS_TOKEN_EXPIRED: "12h"
  JWT_REFRESH_TOKEN_EXPIRED: "168h"
  CRON_SESSION_DEDUPLICATE_ENABLED: "true"
  CRON_SESSION_SUMMARIZE_ENABLED: "true"
  CRON_SESSION_SCORE_ENABLED: "true"
  CRON_SOFT_DELETE_PURGE_ENABLED: "true"
