version: '3'

networks:
  1panel-network:
    external: true

services:

  aris-proxy-api-db-migrate:
    image: ghcr.io/hcd233/aris-proxy-api:master # aris-proxy-api:latest
    container_name: aris-proxy-api-db-migrate
    restart: no
    networks:
      - 1panel-network
    env_file:
      - ../env/api.env
    command: ["/app/aris-proxy-api", "database", "migrate"]

  aris-proxy-api:
    image: ghcr.io/hcd233/aris-proxy-api:master # aris-proxy-api:latest
    container_name: aris-proxy-api
    restart: always
    networks:
      - 1panel-network
    ports:
      - 7070:8080
    env_file:
      - ../env/api.env
    volumes:
      - ../logs:/app/logs
    depends_on:
      aris-proxy-api-db-migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["/app/aris-proxy-api", "server", "start", "--host", "0.0.0.0", "--port", "8080"]

# docker compose -f docker/docker-compose-single.yml up -d
